plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def ksPath = System.getenv('FM_KEYSTORE') ?: 'filemanager-release.keystore'
def ksPass = System.getenv('FM_KEYSTORE_PASS') ?: 'filemanager2024'
def kAlias = System.getenv('FM_KEY_ALIAS') ?: 'filemanagervip'
def kPass = System.getenv('FM_KEY_PASS') ?: 'filemanager2024'

android {
    namespace 'com.filemanager.vip'
    compileSdk 34

    defaultConfig {
        applicationId "com.filemanager.vip"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
        multiDexEnabled true
    }

    signingConfigs {
        release {
            storeFile rootProject.file(ksPath)
            storePassword ksPass
            keyAlias kAlias
            keyPassword kPass
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.7.0'
    implementation 'androidx.lifecycle:lifecycle-process:2.7.0'
    implementation 'androidx.activity:activity-ktx:1.8.2'
    implementation 'androidx.fragment:fragment-ktx:1.6.2'
    implementation 'com.google.android.gms:play-services-ads:22.6.0'
}
